= Setting up OS

This is a short version.
Full descriptions is in the official  https://www.raspberrypi.org/documentation/installation/installing-images/README.md[OS installation guide]

== Prerequisites

- A laptop/desktop with Linux

== Prepare image

- Download the latest Raspberry Pi OS Lite 64-bit, which is a headless version, from https://downloads.raspberrypi.org/raspios_lite_arm64/images/[Raspberry Pi Lite arm64 images page]
- `unxz` the archive to get an `*.img` file

== Setup

- Run `lsblk -p` to find the SD card device and its partition name(s).
It's not going to change if you're using the same SD reader or USB port.

- Set up a new user:
** Run this command to print out encrypted password: `echo 'mypassword' | openssl passwd -6 -stdin`
** Create a file on the computer: `/tmp/userconf` that contains a single line of text:
+
----
pi:encrypted_password
----

- Create a file on the computer: `/tmp/wpa_supplicant.conf` with the content below. Fill in your Wi-Fi network name and password (2.4 GHz network, not 5 GHz). Do it only once and then reuse it for all Pis.
+
----
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=US

network={
    ssid="your-network-name"
    psk="your-network-password"
    key_mgmt=WPA-PSK
}
----

NOTE: The rest of commands below needs to be done N times - for each Pi

Use either xref:_setup_using_script[the script] or xref:_manual_setup[manual steps]. If you do it for the 1st time, then use manual steps to understand what's going on. The script just automates manual steps.

[#_setup_using_script]
== Setup using script

Edit `set-up-os.sh`, specify variables:

- `OS_IMAGE` - path to `*.img` file
- `SD_CARD_DEVICE` - the whole SD card device, which can be found in `lsblk -p` output. For instance: `/dev/mmcblk0`, when plugging it in via build-in card reader, or `/dev/sda`, when plugging it via USB card reader.
- `SD_CARD_PARTITION_BOOT` - boot partition on the SD card, e.g. `/dev/mmcblk0p1` or `/dev/sda1`
- `SD_CARD_PARTITION_ROOTFS` - rootfs partition on the SD card, e.g. `/dev/mmcblk0p2` or `/dev/sda2`. It is present only if the SD card already has OS installed.

WARNING: DO NOT run the script without checking the variables above! You risk wiping another device by mistake.

When you made sure the paths are OK, run the script:

    cd 01-set-up-os
    sudo ./set-up-os.sh

[#_manual_setup]
== Manual setup

=== Copy OS image to micro SD card

- If the SD card is mounted, unmount the partition `umount /dev/mmcblk0p1` (the partition can be found by running `lsblk -p`)
- Copy the image to the SD card (important: use the whole device, not partition):

    sudo dd bs=4M if=2021-05-07-raspios-buster-arm64-lite.img of=/dev/mmcblk0 status=progress conv=fsync

==== Optional: Check if the image was correctly written

- Note the number of `in` records from what dd has printed: `xxx+0 records in`.
Use this number in this command, which will copy the SD card back to the disk as a new image file:

    sudo dd bs=4M if=/dev/mmcblk0 of=from-sd-card.img count=xxx

- Compare the original image with the one copied from the SD card:

    diff -s from-sd-card.img 2021-05-07-raspios-buster-arm64-lite.img

==== Flush. DO NOT FORGET!!!

- Run `sync` to ensure that write cache is flushed and that it is safe to unmount the SD card.

==== Set up a new user

- Copy `/tmp/userconf` file to the boot partition: `sudo cp /tmp/userconf /mnt/sd/boot/`

==== Set up SSH

- Create a directory on the computer to mount the boot partition: `sudo mkdir -p /mnt/sd/boot`
- Mount the boot partition: `sudo mount /dev/mmcblk0p1 /mnt/sd/boot`
- Create empty ssh file: `sudo touch /mnt/sd/boot/ssh`

==== Set up Wi-Fi

- Copy `/tmp/wpa_supplicant.conf` file to the boot partition: `sudo cp /tmp/wpa_supplicant.conf /mnt/sd/boot/`

==== Ready!

- Now the SD card is ready and can be unmounted from the computer `sudo umount /dev/mmcblk0p1`

== Configure Pi OS

NOTE: This also needs to be done N times - for each Pi

- Insert microSD card in the Pi and boot
- Find IP address of the Pi from the computer: `sudo nmap -sP 192.168.0.1/24` (use your subnet range).
The output should have something like:

    Nmap scan report for 192.168.0.12
    Host is up (0.095s latency).
    MAC Address: <mac-address-of-the-pi> (Raspberry Pi Trading)

- SSH on it, e.g. `ssh pi@192.168.0.12`
- Default password is `raspberry`, which needs to be changed immediately.
- Once inside the Pi, run `sudo raspi-config` and follow the wizard to change the password.
- `sudo reboot`
- Connect again
- Run `sudo apt update && sudo apt upgrade -y && sudo apt install -y python3-dev python3-pip libyaml-dev libffi-dev git && sudo pip3 install ansible`

== Copy SSH keys to each Pi

NOTE: This also needs to be done N times - for each Pi

This command will copy the most recent public key that matches `~/.ssh/id*.pub`.
Specific key can be explicitly passed with `-i` argument:

----
ssh-copy-id pi@192.168.0.12
----
