= Install Kubernetes

I'm using K3s from Rancher which is a lightweight K8s distro.
The steps below are based on https://github.com/k3s-io/k3s-ansible

== Run `k3s-ansible` playbook

- Prepare ansible playbook:
+
----
cd 04-install-k8s/k3s-ansible
rm -rf *
rm -rf .*

git clone git@github.com:k3s-io/k3s-ansible.git .

rm -rf .git
git restore .gitignore
----

- Prepare my cluster
+
----
cp -R inventory/sample inventory/my-cluster
cp ../hosts.ini inventory/my-cluster/

vim inventory/my-cluster/group_vars/all.yml
# change ansible_user to pi (or whatever user you created on 01-setup-os step)
----

- Run the playbook:
+
----
ansible-playbook site.yml -i inventory/my-cluster/hosts.ini
----

=== Troubleshooting

==== failed to find memory cgroup (v2)

If k3s service fails to start with `failed to find memory cgroup (v2)` (in `journalctl -xe`), it's probably due to Debian 11 Bullseye is not supported yet.

More details: https://github.com/k3s-io/k3s-ansible/pull/185

Solution: use the code from the CR

== Connect to the control plane

- If everything went well, run this command to copy config from the control plane (master) to your local computer:
+
----
mkdir ~/.kube
scp pi@192.168.0.101:~/.kube/config ~/.kube/config
----

- Identify current k8s version in `04-install-k8s/k3s-ansible/inventory/my-cluster/group_vars/all.yml` > `k3s_version` property. For example: `v1.22.3+k3s1`, here upstream version is `v1.22.3`
- Make sure the same version of `kubectl` is installed on the local computer
+
----
curl -LO https://dl.k8s.io/release/v1.22.3/bin/linux/amd64/kubectl
curl -LO https://dl.k8s.io/v1.22.3/bin/linux/amd64/kubectl.sha256
echo "$(cat kubectl.sha256) kubectl" | sha256sum --check
sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
----

- Validate: `kubectl version`
- Check nodes: `kubectl get nodes`

== Shut down Pis before you unplug them

----
ansible all -i inventory/my-cluster/hosts.ini -a "shutdown now" -b
----
