= Install Kubernetes

I'm using K3s from Rancher which is a lightweight K8s distro.
The steps below are based on https://github.com/k3s-io/k3s-ansible

== Run `k3s-ansible` playbook

- cd to `./05-install-k8s`
- Specify Raspberry Pi's IP addresses in `inventory/hosts.ini`
- Disable swap manually.
I couldn't find a working Ansible role that could disable swap permanently, unfortunately.
So, for now, run it manually N times on each node:

    sudo dphys-swapfile swapoff
    sudo dphys-swapfile uninstall
    sudo update-rc.d dphys-swapfile remove
    sudo apt purge -y dphys-swapfile

- Run the playbook:

    ansible-playbook site.yml -i inventory/hosts.ini

== Connect to the control plane

- If everything went well, run this command to copy config from the control plane (master) to your local computer:

    scp pi@192.168.0.101:~/.kube/config ~/.kube/config

- Make sure is `kubectl` is installed on the local compute, for instance

    sudo apt install -y kubectl

- Validate it with `kubectl version`.
Ideally, client version and server version should match.
- Check nodes: `kubectl get nodes`

== Shut down Pis before you unplug them

    ansible all -i inventory/hosts.ini -a "shutdown now" -b